name: Continuous Deployment
  
on: 
  push:
    branches:
      - master
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        # Konfigurasi key dan password bergantung credentials server yang digunakan
        # Silahkan sesuaikan dengan config server
        # key: ${{ secrets.SSH_KEY }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        # nilai forum bergantung pada penamaan pada saat register ketika menjalankan pm2
        script: |
          cd ~/forum-api
          git pull origin main
          npm install
          npm run migrate up
          pm2 restart forum